### ISSUE TITLE
Need faster private set intersection subroutine

### ISSUE THREAD

**Issue by RiverRuby** [gausslabs/phantom-zone#7]
Many queries I'm interested in making often use a large PSI as a subroutine, and expressing this in binary circuits is much slower than the BFV scheme used in https://github.com/Janmajayamall/MP-PSI.

I think this is fairy high priority for interesting apps to be built that benefit from being multiplayer.

**Comment by Janmajayamall** [comment]
Let's try to view PSI as element-wise multiplication between two vectors. The first being the selector vector and the second being the values. 

For example, 

Encryption of selector vector = ENC(S) => ENC([0, 1, 0, 0, 0, 0, 0, 0])
Encryption of value vector = ENC(V) => ENC([A, B, C, D, E, F, G, H])

ENC(S) x ENC(V) = ENC([0, B, 0, 0, 0, 0, 0, 0])

It will be nice to perform ENC(S) x ENC(V) fast and extract ENC(B) into a single ciphertext and perform other arbitrary operations over ENC(B). I understand that ENC(S) x ENC(V) will be O(N) (although very parallelisable) using FHEW, whereas ENC(S) x ENC(V) can be amortised across a single RLWE multiplication. 

But what happens when no. of bits set to 1 in S are unknown? 

Let's assume S is no more a hot vector. Instead more than 1 values are set to 1. For ex, S has the following shape

ENC(S) => ENC([0, 1, 1, 0, 0, 0, 0, 0])

Then
ENC(S) x ENC(V) = ENC([0, B, C, 0, 0, 0, 0, 0]), 

Since no-one knows that two bits are set to 1 in S, the server will extract all indices and the circuit will have to handle computing on all indices. 

Which is why I'm curious whether the applications you're running into assumes intersection size is known publicly? If yes, then how big is the usual intersection size? If no, then performance wise there will be no difference since you will have to, in the end, operate over all indices. However, we can design better packing srategies for PSI, such that communication cost is minimised. 

BTW PSI using FHEW is very parallelisable. So, in practice, you wouldn't have to wait more than a second or so.
